# fly.toml app configuration file generated for frontend-twilight-surf-2167 on 2024-12-03T23:16:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-twilight-surf-2167'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
