[build]
cmd = "go build -o ./wakana ."
bin = "./wakana"
full_bin = "./wakana serve --config config-wakana.yml"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = [".github", "frontend", "notes", "static"]
