name: ci
on:
  push:
  pull_request:
    workflow_dispatch:
    inputs:
      skip_unit_tests:
        description: "Skip unit tests"
        required: false
        default: "false"

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0 # Replace with your desired Node.js version

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run lint
        run: yarn lint
        working-directory: ./frontend

  test:
    name: "Unit- & API tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23
        id: go

      - name: Get dependencies
        run: go get

      # - name: Unit Tests
      #   run: CGO_ENABLED=0 go test `go list ./... | grep -v 'github.com/muety/wakapi/scripts'` -run ./... # skip scripts package, because not actually a package

      # - name: API Tests
      #   run: |
      #     npm -g install newman
      #     ./testing/run_api_tests.sh

      - name: Mail Tests
        run: ./testing/run_mail_tests.sh

  migration:
    name: Migration tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        db: [postgres]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23
        id: go

      - run: ./testing/run_api_tests.sh ${{ matrix.db }} --migration
